---
spring:
  jpa:
    hibernate.ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
  liquibase:
    enabled: true
  data:
    rest:
      base-path: /api
      default-page-size: 10
      return-body-on-update: false
      max-page-size: 50
google-client-id: ${GOOGLE_CLIENT_ID}

---
profile: local

spring:
  datasource:
    url: ${LOCAL_DATABASE_URL}
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-local.yaml

---
profile: dev

spring:
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: com.mysql.jdbc.Driver
  liquibase:
    enabled: false
    change-log: classpath:/db/changelog/db.changelog-dev.yaml
